---
title: "Welcome to my blog"
date: 2020-01-15
---
theme: minima
author: GitHub User
email: Test@github
description: > # this means to ignore newlines until "baseurl:"
  Passion on Science and Data

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
